version: "3"

services:
  postgres:
    container_name: tabadol_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - back-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: tabadol_redis
    image: ${REDIS_IMAGE}
    networks:
      - back-network

  tabadol_api:
    container_name: tabadol_api
    image: registry.aasaam.org:5600/tabadol:latest
    networks:
      - back-network
      - front-network
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=PRODUCTION
      - POSTGRES_URI=postgres://example:example@tabadol_postgres:5432/tabadol_postgres
      - REDIS_URI=redis://tabadol_redis:6379
      - API_PUBLIC_URL=http://127.0.0.1:8081
    volumes:
      - files-storage:/storage/files

  tabadol_front:
    container_name: tabadol_front
    image: ${TABADOL_FRONT_IMAGE}
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
      - files-storage:/storage/files:ro
      - ./app:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - tabadol_api
    networks:
      - front-network
    #command: tail -f /dev/null

networks:
  back-network:
  front-network:
volumes:
  files-storage:
  db-data:
